# =============================================================================
# AAP Terraform Actions - Taskfile
# =============================================================================
# Comprehensive build and deploy commands for:
#   - AAP deployment (pre-built AMI)
#   - Packer golden VM image (RHEL9 with Vault SSH CA)
#   - Terraform infrastructure (VM + AAP integration)
#   - Vault SSH CA operations
#
# Credential Options:
#   - Option A: Vault Signed SSH (static key, /ssh/sign)
#   - Option B: Vault Secrets Lookup (ephemeral keys, /ssh/issue)
#
# https://taskfile.dev
# =============================================================================

version: "3"

vars:
  # Directories
  TF_AAP_DIR: ./terraform/aap
  TF_INFRA_DIR: ./terraform/infra
  PACKER_VM_DIR: ./packer/vm-golden-image

  # Defaults (override via environment or CLI)
  AWS_REGION: '{{.AWS_REGION | default "us-east-1"}}'
  VAULT_SSH_MOUNT: '{{.VAULT_SSH_MOUNT | default "ssh"}}'
  VAULT_SSH_ROLE: '{{.VAULT_SSH_ROLE | default "aap-ssh"}}'

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list

  # ===========================================================================
  # Prerequisites & Setup
  # ===========================================================================

  check:
    desc: Check all prerequisites
    cmds:
      - |
        echo "═══════════════════════════════════════════════════════════════"
        echo " Checking Prerequisites"
        echo "═══════════════════════════════════════════════════════════════"
      - |
        echo -n "Terraform: "
        if command -v terraform &>/dev/null; then
          TF_VERSION=$(terraform version -json | jq -r '.terraform_version')
          echo "$TF_VERSION"
          MAJOR=$(echo $TF_VERSION | cut -d. -f1)
          MINOR=$(echo $TF_VERSION | cut -d. -f2)
          if [ "$MAJOR" -lt 1 ] || ([ "$MAJOR" -eq 1 ] && [ "$MINOR" -lt 14 ]); then
            echo "  ⚠ WARNING: Terraform 1.14+ required for Actions"
          else
            echo "  ✓ Version OK (Actions supported)"
          fi
        else
          echo "NOT FOUND ✗"
        fi
      - |
        echo -n "Packer: "
        if command -v packer &>/dev/null; then
          packer version | head -1
        else
          echo "NOT FOUND ✗"
        fi
      - |
        echo -n "AWS CLI: "
        if command -v aws &>/dev/null; then
          aws --version 2>&1 | head -1
        else
          echo "NOT FOUND ✗"
        fi
      - |
        echo -n "Vault CLI: "
        if command -v vault &>/dev/null; then
          vault version
        else
          echo "NOT FOUND (optional)"
        fi
      - |
        echo ""
        echo "Environment Variables:"
        echo -n "  VAULT_ADDR: "
        if [ -n "$VAULT_ADDR" ]; then echo "$VAULT_ADDR"; else echo "NOT SET"; fi
        echo -n "  VAULT_TOKEN: "
        if [ -n "$VAULT_TOKEN" ]; then echo "SET (hidden)"; else echo "NOT SET"; fi
        echo -n "  VAULT_NAMESPACE: "
        if [ -n "$VAULT_NAMESPACE" ]; then echo "$VAULT_NAMESPACE"; else echo "NOT SET"; fi
        echo -n "  AWS_REGION: "
        if [ -n "$AWS_REGION" ]; then echo "$AWS_REGION"; else echo "NOT SET (default: us-east-1)"; fi
    silent: true

  # ===========================================================================
  # Packer - Golden VM Image (RHEL9 with Vault SSH CA)
  # ===========================================================================

  packer:init:
    desc: Initialize Packer for VM golden image
    dir: "{{.PACKER_VM_DIR}}"
    cmds:
      - packer init .

  packer:validate:
    desc: Validate VM golden image Packer config
    dir: "{{.PACKER_VM_DIR}}"
    cmds:
      - packer validate .
    vars:
      VAULT_SSH_CA_PUBLIC_KEY: '{{.VAULT_SSH_CA_PUBLIC_KEY | default "dummy-key-for-validation"}}'

  packer:build:
    desc: Build VM golden image with Vault SSH CA
    dir: "{{.PACKER_VM_DIR}}"
    cmds:
      - |
        if [ -z "$VAULT_SSH_CA_PUBLIC_KEY" ]; then
          echo "Fetching Vault SSH CA public key..."
          export VAULT_SSH_CA_PUBLIC_KEY=$(vault read -field=public_key {{.VAULT_SSH_MOUNT}}/config/ca)
        fi
        packer build \
          -var "vault_ssh_ca_public_key=$VAULT_SSH_CA_PUBLIC_KEY" \
          -var "aws_region={{.AWS_REGION}}" \
          .
    env:
      PACKER_LOG: "1"

  packer:build:auto:
    desc: Build VM golden image (auto-fetch CA key from Vault)
    dir: "{{.PACKER_VM_DIR}}"
    cmds:
      - |
        echo "Fetching Vault SSH CA public key..."
        VAULT_SSH_CA_PUBLIC_KEY=$(vault read -field=public_key {{.VAULT_SSH_MOUNT}}/config/ca)
        echo "Building golden VM image..."
        packer build \
          -var "vault_ssh_ca_public_key=$VAULT_SSH_CA_PUBLIC_KEY" \
          -var "aws_region={{.AWS_REGION}}" \
          .

  # ===========================================================================
  # AAP Controller Deployment (pre-built AMI)
  # ===========================================================================

  aap:init:
    desc: Initialize Terraform for AAP deployment
    dir: "{{.TF_AAP_DIR}}"
    cmds:
      - terraform init

  aap:plan:
    desc: Plan AAP deployment
    dir: "{{.TF_AAP_DIR}}"
    cmds:
      - terraform plan

  aap:deploy:
    desc: Deploy AAP controller (pre-built AMI)
    dir: "{{.TF_AAP_DIR}}"
    cmds:
      - |
        echo "═══════════════════════════════════════════════════════════════"
        echo " Deploying AAP Controller"
        echo "═══════════════════════════════════════════════════════════════"
        echo ""
        echo "Using pre-built AAP AMI"
        echo "Region: {{.AWS_REGION}}"
        echo ""
      - terraform apply
      - |
        echo ""
        echo "═══════════════════════════════════════════════════════════════"
        echo " AAP Deployment Complete"
        echo "═══════════════════════════════════════════════════════════════"
        terraform output -raw aap_url 2>/dev/null && echo "" || true
        echo ""
        echo "Credentials:"
        echo "  Username: $(terraform output -raw aap_username)"
        echo "  Password: $(terraform output -raw aap_password)"
        echo ""
        echo "Next steps:"
        echo "  1. Copy AAP outputs to terraform/infra/terraform.tfvars"
        echo "  2. Run: task infra:deploy"

  aap:deploy:auto:
    desc: Deploy AAP controller (auto-approve)
    dir: "{{.TF_AAP_DIR}}"
    cmds:
      - terraform apply -auto-approve

  aap:destroy:
    desc: Destroy AAP controller
    dir: "{{.TF_AAP_DIR}}"
    cmds:
      - terraform destroy

  aap:output:
    desc: Show AAP outputs (for infra config)
    dir: "{{.TF_AAP_DIR}}"
    cmds:
      - |
        echo "═══════════════════════════════════════════════════════════════"
        echo " AAP Outputs (copy to terraform/infra/terraform.tfvars)"
        echo "═══════════════════════════════════════════════════════════════"
        echo ""
        terraform output

  aap:ssh:
    desc: SSH into AAP controller
    dir: "{{.TF_AAP_DIR}}"
    cmds:
      - |
        AAP_IP=$(terraform output -raw aap_public_ip 2>/dev/null)
        if [ -z "$AAP_IP" ] || [ "$AAP_IP" = "null" ]; then
          echo "ERROR: AAP not deployed. Run 'task aap:deploy' first."
          exit 1
        fi
        terraform output -raw aap_private_key > /tmp/aap-key && chmod 600 /tmp/aap-key
        ssh -i /tmp/aap-key -o StrictHostKeyChecking=no ec2-user@$AAP_IP

  aap:info:
    desc: Show AAP connection info
    dir: "{{.TF_AAP_DIR}}"
    cmds:
      - |
        echo "═══════════════════════════════════════════════════════════════"
        echo " AAP Controller Info"
        echo "═══════════════════════════════════════════════════════════════"
        echo ""
        AAP_IP=$(terraform output -raw aap_public_ip 2>/dev/null)
        if [ -z "$AAP_IP" ] || [ "$AAP_IP" = "null" ]; then
          echo "AAP not deployed. Run 'task aap:deploy' first."
          exit 0
        fi
        echo "URL:         https://$AAP_IP"
        echo "Username:    $(terraform output -raw aap_username)"
        echo "Password:    $(terraform output -raw aap_password)"
        echo ""
        echo "SSH Command: task aap:ssh"

  # ===========================================================================
  # Infrastructure Deployment (VMs + AAP Integration)
  # ===========================================================================

  infra:init:
    desc: Initialize Terraform for infrastructure
    dir: "{{.TF_INFRA_DIR}}"
    cmds:
      - terraform init

  infra:init:upgrade:
    desc: Upgrade Terraform providers
    dir: "{{.TF_INFRA_DIR}}"
    cmds:
      - terraform init -upgrade

  infra:validate:
    desc: Validate Terraform configuration
    dir: "{{.TF_INFRA_DIR}}"
    cmds:
      - terraform validate

  infra:plan:
    desc: Plan infrastructure (default credential option)
    dir: "{{.TF_INFRA_DIR}}"
    cmds:
      - terraform plan

  infra:plan:option-a:
    desc: Plan with Option A (Vault Signed SSH)
    dir: "{{.TF_INFRA_DIR}}"
    cmds:
      - terraform plan -var="credential_option=A"

  infra:plan:option-b:
    desc: Plan with Option B (Vault Secrets Lookup - ephemeral)
    dir: "{{.TF_INFRA_DIR}}"
    cmds:
      - terraform plan -var="credential_option=B"

  infra:deploy:
    desc: Deploy infrastructure (creates VMs + triggers AAP)
    dir: "{{.TF_INFRA_DIR}}"
    cmds:
      - terraform apply

  infra:deploy:auto:
    desc: Deploy infrastructure (auto-approve)
    dir: "{{.TF_INFRA_DIR}}"
    cmds:
      - terraform apply -auto-approve

  infra:deploy:option-a:
    desc: Deploy with Option A (Vault Signed SSH)
    dir: "{{.TF_INFRA_DIR}}"
    cmds:
      - terraform apply -var="credential_option=A"

  infra:deploy:option-b:
    desc: Deploy with Option B (Vault Secrets Lookup - ephemeral)
    dir: "{{.TF_INFRA_DIR}}"
    cmds:
      - terraform apply -var="credential_option=B"

  infra:destroy:
    desc: Destroy infrastructure
    dir: "{{.TF_INFRA_DIR}}"
    cmds:
      - terraform destroy

  infra:output:
    desc: Show infrastructure outputs
    dir: "{{.TF_INFRA_DIR}}"
    cmds:
      - terraform output

  # ===========================================================================
  # Vault Operations
  # ===========================================================================

  vault:status:
    desc: Check Vault SSH CA status
    cmds:
      - |
        echo "═══════════════════════════════════════════════════════════════"
        echo " Vault SSH CA Status"
        echo "═══════════════════════════════════════════════════════════════"
        echo ""
        echo "SSH secrets engine:"
        vault secrets list | grep -E "^{{.VAULT_SSH_MOUNT}}/" || echo "  Not found at {{.VAULT_SSH_MOUNT}}/"
        echo ""
        echo "SSH signing roles:"
        vault list {{.VAULT_SSH_MOUNT}}/roles 2>/dev/null || echo "  No roles found"
        echo ""
        echo "AppRole auth:"
        vault auth list | grep approle || echo "  AppRole auth not enabled"

  vault:ca-key:
    desc: Get Vault SSH CA public key
    cmds:
      - vault read -field=public_key {{.VAULT_SSH_MOUNT}}/config/ca

  vault:test:sign:
    desc: Test /ssh/sign endpoint (Option A)
    cmds:
      - |
        echo "Generating test key pair..."
        TMPDIR=$(mktemp -d)
        ssh-keygen -t ed25519 -f "$TMPDIR/test_key" -N "" -q
        echo ""
        echo "Requesting signed certificate from Vault..."
        vault write -field=signed_key {{.VAULT_SSH_MOUNT}}/sign/{{.VAULT_SSH_ROLE}} \
          public_key=@"$TMPDIR/test_key.pub" \
          ttl=5m > "$TMPDIR/test_key-cert.pub"
        echo ""
        echo "Certificate details:"
        ssh-keygen -L -f "$TMPDIR/test_key-cert.pub"
        rm -rf "$TMPDIR"
        echo ""
        echo "✓ Test certificate signed successfully!"

  vault:test:issue:
    desc: Test /ssh/issue endpoint (Option B)
    cmds:
      - |
        echo "Testing SSH key issuance from Vault..."
        RESULT=$(vault write -format=json {{.VAULT_SSH_MOUNT}}/issue/{{.VAULT_SSH_ROLE}} key_type=rsa key_bits=4096)
        echo ""
        echo "Success! Received:"
        echo "  - Private key: $(echo $RESULT | jq -r '.data.private_key' | head -1)..."
        echo "  - Signed cert: $(echo $RESULT | jq -r '.data.signed_key' | head -1)..."
        echo ""
        echo "Certificate details:"
        echo "$RESULT" | jq -r '.data.signed_key' | ssh-keygen -L -f -

  # ===========================================================================
  # Demo Flows
  # ===========================================================================

  demo:option-a:
    desc: Full demo with Option A (Vault Signed SSH)
    cmds:
      - task: check
      - |
        echo ""
        echo "═══════════════════════════════════════════════════════════════"
        echo " Demo: Option A - Vault Signed SSH"
        echo "═══════════════════════════════════════════════════════════════"
        echo ""
        echo "This demo uses a static SSH key stored in AAP."
        echo "The key is signed by Vault SSH CA before each connection."
        echo ""
      - task: aap:init
      - task: aap:deploy
      - |
        echo ""
        echo "Configuring infrastructure with AAP outputs..."
      - task: infra:init
      - task: infra:deploy:option-a

  demo:option-b:
    desc: Full demo with Option B (Vault Secrets Lookup - ephemeral)
    cmds:
      - task: check
      - |
        echo ""
        echo "═══════════════════════════════════════════════════════════════"
        echo " Demo: Option B - Vault Secrets Lookup (Ephemeral Keys)"
        echo "═══════════════════════════════════════════════════════════════"
        echo ""
        echo "This demo uses ephemeral SSH key pairs generated on-demand."
        echo "No static keys are stored - all credentials are short-lived."
        echo ""
      - task: aap:init
      - task: aap:deploy
      - |
        echo ""
        echo "Configuring infrastructure with AAP outputs..."
      - task: infra:init
      - task: infra:deploy:option-b

  demo:full:
    desc: Full demo (build golden image + deploy all)
    cmds:
      - task: check
      - |
        echo ""
        echo "═══════════════════════════════════════════════════════════════"
        echo " Full Demo: Build Golden Image + Deploy Infrastructure"
        echo "═══════════════════════════════════════════════════════════════"
      - task: packer:build:auto
      - task: aap:init
      - task: aap:deploy
      - task: infra:init
      - task: infra:deploy

  # ===========================================================================
  # Cleanup
  # ===========================================================================

  clean:infra:
    desc: Clean infrastructure Terraform state
    cmds:
      - |
        echo "Cleaning infrastructure Terraform state..."
        rm -rf {{.TF_INFRA_DIR}}/.terraform {{.TF_INFRA_DIR}}/.terraform.lock.hcl
        rm -rf {{.TF_INFRA_DIR}}/terraform.tfstate* {{.TF_INFRA_DIR}}/.terraform.tfstate.lock.info
        echo "Done!"

  clean:aap:
    desc: Clean AAP Terraform state
    cmds:
      - |
        echo "Cleaning AAP Terraform state..."
        rm -rf {{.TF_AAP_DIR}}/.terraform {{.TF_AAP_DIR}}/.terraform.lock.hcl
        rm -rf {{.TF_AAP_DIR}}/terraform.tfstate* {{.TF_AAP_DIR}}/.terraform.tfstate.lock.info
        echo "Done!"

  clean:packer:
    desc: Clean Packer caches
    cmds:
      - |
        echo "Cleaning Packer caches..."
        rm -rf {{.PACKER_VM_DIR}}/packer_cache
        echo "Done!"

  clean:all:
    desc: Clean everything (all Terraform state + Packer cache)
    cmds:
      - task: clean:infra
      - task: clean:aap
      - task: clean:packer
