# =============================================================================
# AAP Terraform Actions - Taskfile
# =============================================================================
# Simplified build and deploy commands:
#   - Packer: Build golden VM image
#   - Terraform: Deploy infrastructure
#   - Demo: End-to-end workflows
#
# https://taskfile.dev
# =============================================================================

version: "3"

vars:
  TF_DIR: ./terraform/infra
  PACKER_DIR: ./packer/vm-golden-image
  AWS_REGION: '{{.AWS_REGION | default "us-east-1"}}'
  VAULT_SSH_MOUNT: '{{.VAULT_SSH_MOUNT | default "ssh"}}'
  VAULT_SSH_ROLE: '{{.VAULT_SSH_ROLE | default "aap-ssh"}}'

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list

  # ===========================================================================
  # Prerequisites
  # ===========================================================================

  check:
    desc: Check prerequisites (terraform, packer, aws, vault)
    cmds:
      - |
        echo "Checking prerequisites..."
        for cmd in terraform packer aws vault; do
          printf "  %-12s" "$cmd:"
          if command -v $cmd &>/dev/null; then
            $cmd version 2>/dev/null | head -1 || echo "OK"
          else
            echo "NOT FOUND"
          fi
        done
        echo ""
        echo "Environment:"
        echo "  VAULT_ADDR: ${VAULT_ADDR:-NOT SET}"
        echo "  VAULT_TOKEN: ${VAULT_TOKEN:+SET}"
    silent: true

  # ===========================================================================
  # Packer
  # ===========================================================================

  packer:build:
    desc: Build golden VM image with Vault SSH CA
    dir: "{{.PACKER_DIR}}"
    cmds:
      - packer init .
      - |
        if [ -z "$VAULT_SSH_CA_PUBLIC_KEY" ]; then
          echo "Fetching Vault SSH CA public key..."
          export VAULT_SSH_CA_PUBLIC_KEY=$(vault read -field=public_key {{.VAULT_SSH_MOUNT}}/config/ca)
        fi
        packer build \
          -var "vault_ssh_ca_public_key=$VAULT_SSH_CA_PUBLIC_KEY" \
          -var "aws_region={{.AWS_REGION}}" \
          .

  # ===========================================================================
  # Terraform
  # ===========================================================================

  tf:init:
    desc: Initialize Terraform
    dir: "{{.TF_DIR}}"
    cmds:
      - terraform init

  tf:plan:
    desc: Plan infrastructure changes
    dir: "{{.TF_DIR}}"
    cmds:
      - terraform plan

  tf:apply:
    desc: Deploy infrastructure
    dir: "{{.TF_DIR}}"
    cmds:
      - terraform apply -auto-approve

  tf:destroy:
    desc: Destroy infrastructure
    dir: "{{.TF_DIR}}"
    cmds:
      - terraform destroy

  tf:output:
    desc: Show Terraform outputs
    dir: "{{.TF_DIR}}"
    cmds:
      - terraform output

  # ===========================================================================
  # Demos
  # ===========================================================================

  demo:
    desc: "Demo: Deploy VMs and trigger AAP configuration"
    cmds:
      - task: check
      - task: tf:init
      - terraform -chdir={{.TF_DIR}} apply -auto-approve
      - echo ""
      - echo "Demo deployed! Check AAP for job status."
      - terraform -chdir={{.TF_DIR}} output -raw ssh_command

  demo:full:
    desc: "Demo: Build Packer image + deploy infrastructure"
    cmds:
      - task: check
      - task: packer:build
      - task: tf:init
      - terraform -chdir={{.TF_DIR}} apply -auto-approve

  # ===========================================================================
  # Cleanup
  # ===========================================================================

  clean:
    desc: Clean Terraform state and Packer cache
    cmds:
      - rm -rf {{.TF_DIR}}/.terraform {{.TF_DIR}}/.terraform.lock.hcl
      - rm -rf {{.TF_DIR}}/terraform.tfstate*
      - rm -rf {{.PACKER_DIR}}/packer_cache
      - echo "Cleaned!"
